# Generated by Django 5.2.5 on 2025-10-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0005_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='user.jpg', upload_to='profile_pics/'),
        ),
    ]
